name: Deploy Web

on:
  push:
    branches: [main]

jobs:
  trigger-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Trigger infrastructure deploy
        uses: peter-evans/repository-dispatch@v3
        with:
          token: ${{ secrets.DEPLOY_TOKEN }}
          repository: velddev/ventured-infrastructure
          event-type: deploy-frontend
